# Generated by Django 5.0.4 on 2025-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional context for the question', max_length=500, verbose_name='help text'),
        ),
    ]
